# Generated by Django 4.2.6 on 2023-10-28 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_post_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='favorite_count',
            field=models.IntegerField(default=0),
        ),
    ]
